/**
 * Initialize asset step outputs from visual_direction scene definitions.
 *
 * Visual direction is the source of truth for which scenes exist.
 * This creates/rebuilds step outputs for image_generation, hero_scenes,
 * and stock_footage with the correct scene arrays, carrying forward any
 * existing manual uploads that match by scene_id or array position.
 *
 * Called from save/route.ts, llm-callback/route.ts, and the init-slots API.
 */

import { upsertStep, getStepsByProject } from "@/lib/store";
import { parseDalleScenes, parseRunwayScenes, parseStockScenes } from "@/lib/pipeline/parse-visual-scenes";
import type { SceneImage, SceneVideo } from "@/types";

/**
 * After visual_direction completes, create/rebuild step outputs for:
 * - image_generation: scenes[] with DALL-E prompts
 * - hero_scenes: scenes[] with Runway prompts
 * - stock_footage: footage[] with STOCK queries
 *
 * Always rebuilds from visual direction as source of truth.
 * Carries forward existing completed assets by matching scene_id.
 */
export async function initializeAssetSlots(projectId: string, visualsRaw: string): Promise<void> {
  const existingSteps = await getStepsByProject(projectId);
  const now = new Date().toISOString();

  // ── Image Generation (DALL-E) ──
  const dalleScenes = parseDalleScenes(visualsRaw);
  if (dalleScenes.length > 0) {
    const imageStep = existingSteps.find(s => s.step === "image_generation");
    // Don't overwrite a fully completed step (all scenes generated by worker)
    const prevScenes = (imageStep?.output as { scenes?: SceneImage[] } | undefined)?.scenes || [];
    const allDone = prevScenes.length > 0 && prevScenes.every(s => s.status === "completed" && s.image_url);

    if (!allDone) {
      // Carry forward any completed scenes by scene_id
      const completedById = new Map(
        prevScenes.filter(s => s.status === "completed" && s.image_url).map(s => [s.scene_id, s]),
      );
      const scenes: SceneImage[] = dalleScenes.map(scene => {
        const existing = completedById.get(scene.scene_id);
        return existing ? { ...scene, image_url: existing.image_url, revised_prompt: existing.revised_prompt, status: "completed" as const } : scene;
      });
      const completedCount = scenes.filter(s => s.status === "completed").length;

      await upsertStep(projectId, "image_generation", {
        status: "pending",
        output: {
          scenes,
          total_prompts: scenes.length,
          generated: completedCount,
          status: completedCount === scenes.length ? "completed" : "awaiting_assets",
        },
        modified_at: now,
      } as Record<string, unknown>);
      console.log(`[init-slots] image_generation: ${scenes.length} slots (${completedCount} pre-filled)`);
    }
  }

  // ── Hero Scenes (Runway) ──
  const runwayScenes = parseRunwayScenes(visualsRaw);
  if (runwayScenes.length > 0) {
    const heroStep = existingSteps.find(s => s.step === "hero_scenes");
    const prevScenes = (heroStep?.output as { scenes?: SceneVideo[] } | undefined)?.scenes || [];
    const allDone = prevScenes.length > 0 && prevScenes.every(s => s.status === "completed" && s.video_url);

    if (!allDone) {
      const completedById = new Map(
        prevScenes.filter(s => s.status === "completed" && s.video_url).map(s => [s.scene_id, s]),
      );
      const scenes: SceneVideo[] = runwayScenes.map(scene => {
        const existing = completedById.get(scene.scene_id);
        return existing ? { ...scene, video_url: existing.video_url, task_id: existing.task_id, status: "completed" as const } : scene;
      });
      const completedCount = scenes.filter(s => s.status === "completed").length;

      await upsertStep(projectId, "hero_scenes", {
        status: "pending",
        output: {
          scenes,
          total_requested: scenes.length,
          status: completedCount === scenes.length ? "completed" : "awaiting_assets",
        },
        modified_at: now,
      } as Record<string, unknown>);
      console.log(`[init-slots] hero_scenes: ${scenes.length} slots (${completedCount} pre-filled)`);
    }
  }

  // ── Stock Footage ──
  const stockScenes = parseStockScenes(visualsRaw);
  if (stockScenes.length > 0) {
    const stockStep = existingSteps.find(s => s.step === "stock_footage");
    const prevFootage = (stockStep?.output as { footage?: Record<string, unknown>[] } | undefined)?.footage || [];

    // Carry forward videos from existing footage entries that match by scene_id
    const prevBySceneId = new Map(
      prevFootage.filter(f => f.scene_id != null).map(f => [f.scene_id as number, f]),
    );

    const footage = stockScenes.map(s => {
      const existing = prevBySceneId.get(s.scene_id);
      const videos = existing?.videos as { file_url?: string }[] | undefined;
      const hasVideo = videos && videos.length > 0 && videos[0]?.file_url;
      return {
        scene_id: s.scene_id,
        query: s.query,
        label: s.label,
        videos: hasVideo ? videos : [],
        ...(existing?.source ? { source: existing.source } : {}),
      };
    });
    const filledCount = footage.filter(f => {
      const v = f.videos as { file_url?: string }[];
      return v.length > 0 && v[0]?.file_url;
    }).length;

    await upsertStep(projectId, "stock_footage", {
      status: "pending",
      output: {
        footage,
        total_queries: footage.length,
        status: filledCount === footage.length ? "completed" : "awaiting_assets",
      },
      modified_at: now,
    } as Record<string, unknown>);
    console.log(`[init-slots] stock_footage: ${footage.length} slots (${filledCount} pre-filled)`);
  }

  console.log(`[init-slots] Asset slots initialized for project ${projectId}`);
}
